# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec for Crimson Desert Ultimate Mods Manager

a = Analysis(
    ['src/cdumm/main.py'],
    pathex=['src'],
    binaries=[],
    datas=[('cdumm.ico', '.')],
    hiddenimports=[
        'cdumm.gui.main_window',
        'cdumm.gui.setup_dialog',
        'cdumm.gui.import_widget',
        'cdumm.gui.conflict_view',
        'cdumm.gui.mod_list_model',
        'cdumm.gui.asi_panel',
        'cdumm.gui.test_mod_dialog',
        'cdumm.gui.workers',
        'cdumm.gui.bug_report',
        'cdumm.engine.snapshot_manager',
        'cdumm.engine.delta_engine',
        'cdumm.engine.import_handler',
        'cdumm.engine.conflict_detector',
        'cdumm.engine.apply_engine',
        'cdumm.engine.mod_manager',
        'cdumm.engine.test_mod_checker',
        'cdumm.archive.transactional_io',
        'cdumm.archive.hashlittle',
        'cdumm.archive.papgt_manager',
        'cdumm.archive.format_parsers.base',
        'cdumm.archive.format_parsers.pabgb_parser',
        'cdumm.archive.format_parsers.paac_parser',
        'cdumm.archive.format_parsers.pamt_parser',
        'cdumm.archive.paz_parse',
        'cdumm.engine.mod_health_check',
        'cdumm.gui.health_check_dialog',
        'cdumm.asi.asi_manager',
        'cdumm.storage.database',
        'cdumm.storage.config',
        'cdumm.storage.game_finder',
        'cdumm.gui.splash',
        'cdumm.gui.mod_contents_dialog',
        'cdumm.gui.profile_dialog',
        'cdumm.engine.update_checker',
        'cdumm.engine.version_detector',
        'cdumm.engine.profile_manager',
        'cdumm.engine.mod_list_io',
        'cdumm.gui.update_overlay',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'PySide6.QtWebEngine', 'PySide6.QtWebEngineWidgets', 'PySide6.QtWebEngineCore',
        'PySide6.Qt3DCore', 'PySide6.Qt3DRender', 'PySide6.Qt3DInput',
        'PySide6.QtCharts', 'PySide6.QtMultimedia', 'PySide6.QtMultimediaWidgets',
        'PySide6.QtQuick', 'PySide6.QtQml', 'PySide6.QtBluetooth',
        'PySide6.QtPositioning', 'PySide6.QtSensors', 'PySide6.QtSerialPort',
        'PySide6.QtRemoteObjects', 'PySide6.QtNfc',
    ],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='CDUMM',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    icon='cdumm.ico',
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
